# Generated by Django 5.2.8 on 2026-04-29 19:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('health', 'Health & Medical'), ('education', 'Education'), ('travel', 'Travel'), ('income', 'Income'), ('other', 'Other')], max_length=20)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('month', models.DateField(help_text='First day of the month this budget applies to.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'category', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in user currency.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('health', 'Health & Medical'), ('education', 'Education'), ('travel', 'Travel'), ('income', 'Income'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(help_text='Date of the transaction.')),
                ('description', models.TextField(blank=True, default='')),
                ('is_income', models.BooleanField(default=False, help_text='True if this is an income entry, False for expense.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='expenses_ex_user_id_4af51e_idx'), models.Index(fields=['user', 'category'], name='expenses_ex_user_id_207090_idx')],
            },
        ),
    ]
